### ISSUE TITLE
undefined method `init_from_source' for DuperVisor:Module (NoMethodError)

### ISSUE THREAD

**Issue by probonopd** [kigster/dupervisor#1]
Getting errors like this lately:

```
+dv database/Nuclino/nuclino-desktop.desktop --yaml -o database/Nuclino/desktop.yaml
/home/travis/.rvm/gems/ruby-2.4.1/gems/dupervisor-1.0.4/lib/dupervisor.rb:5:in `<module:DuperVisor>': undefined method `init_from_source' for DuperVisor:Module (NoMethodError)
```

Do you have an idea what might be causing this?

Reference:
https://github.com/AppImage/appimage.github.io/issues/463

**Comment by kigster** [comment]
Thanks for reporting! Hopefully fixed.

**Comment by kigster** [comment]
Fixed with 052321c62ca677aa41b01e8e6fd8a6dfb5f1644f

**Comment by kigster** [comment]
Please update to version 1.0.5 of the gem. Thanks!

**Comment by probonopd** [comment]
Thanks, works for me.
